import './globals.css'
import { Inter } from 'next/font/google'
import Navigation from './components/Navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'My first app',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <head>
        <link rel="stylesheet" href="https://bootswatch.com/5/vapor/bootstrap.min.css" />
      </head>
      <body className={`${inter.classNameName}`}>
        <Navigation />
        <div className=' container p-4'>
          {children} 
        </div>
        </body>
    </html>
  )
}
